# Generated by Django 4.2.4 on 2023-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок контент-блока')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('views', models.IntegerField(verbose_name='Количество показов')),
            ],
            options={
                'verbose_name': 'Контент-блок',
                'verbose_name_plural': 'Контент-блоки',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, verbose_name='Название в виде url')),
                ('content_blocks', models.ManyToManyField(related_name='content_blocks', to='pages.contentblock', verbose_name='Контент-блоки')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
