# Generated by Django 4.2.4 on 2023-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество показов'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Название в виде url'),
        ),
    ]
