# Generated by Django 4.2.4 on 2023-08-15 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contentblock_views_alter_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions_quantity', models.IntegerField(default=0, editable=False, verbose_name='Количество показов на конкретной странице')),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_block', to='pages.contentblock', verbose_name='Контент-блок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression', to='pages.page', verbose_name='Страница на которой находится контент-блок')),
            ],
        ),
    ]
