# Generated by Django 4.2.4 on 2023-08-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_impression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='content_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression', to='pages.contentblock', verbose_name='Контент-блок'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='impressions_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество показов на конкретной странице'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='pages.page', verbose_name='Страница на которой находится контент-блок'),
        ),
    ]
